export const TRANSLATE = {
  "en": {
    RESERVATION: "Reservation",
    AccountId: "Account Id",
    AccountName: "Account Name",
    AccountImage:"Account Image",
    CopyfromRestaurant:"Copy from Restaurant",
    LatitudePosition:"Latitude Position",
    LongitudePosition:"Longitude Position",
    AddressLine1:"Address Line 1",
    AddressLine2:"Address Line 2",
    AddressLine3:"Address Line 3",
    Country:"Country",
    City:"City",
    Location:"Location",
    OtherLocation:"Other Location    ",
    PinCode:"Pin Code",
    NearLandmark:"Near Landmark",
    TypeofEstablishment:"Type of Establishment",
    KnownFor:"Known For",
    MobileNumber1:"Mobile Number 1",
    MobileNumber2:"Mobile Number 2",
    LandlineNumber1:"Landline Number 1",
    LandlineNumber2:"Landline Number 2",
    EmailId:"Email Id",
    RestaurantWebsite:"Restaurant Website",
    TypeofBusiness:"Type of Business",
    AvgMealPricefor2Persons:"Avg Meal Price for 2 Persons",
    OpeningHours:"Opening Hours",
    From:"From",
    To:"To",
    LiquorAvailable:"Liquor Available",
    LiquorTypes:"Liquor Types",
    Cuisines:"Cuisines",
    HappyHoursOffers:"Happy Hours/ Offers",
    CreditCardsAccepted:"Credit Cards Accepted",
    TimingofHappyHours:"Timing of Happy Hours ",
    FoodPreference:"Food Preference",
    HomeDeliveryFacility:"Home Delivery Facility",
    HomeDeliveryMinBillValue:"Home Delivery Min. Bill Value",
    DeliveryMaxDistance:"Delivery Max Distance",
    FacebookPageExists:"Facebook Page Exists",
    FineDiningAvailable:"Fine Dining Available",
    ValetParking:"Valet Parking",
    Breakfast:"Breakfast",
    TableBookingFacility:"Table Booking Facility",
    Buffet:"Buffet",
    LunchBuffet:"Lunch Buffet",
    WiFiAvailable:"WiFi Available",
    AirConditioning:"Air Conditioning",
    Outdoorseating:"Outdoor seating",
    PetFriendly:"Pet Friendly",
    KidsFriendly:"Kids Friendly",
    ScreensforViewing:"Screens for Viewing",
    SmokingArea:"Smoking Area",
    LateNightEats:"Late Night Eats",
    DedicatedParking:"Dedicated Parking",
    RoofTop:"Roof Top",
    PoolSide:"Pool Side",
    FamilyArea:"Family Area",
    DifferentlyabledPeoplefriendly:"Differently abled People friendly",
    BrailleMenu:"Braille Menu",
    KidsMenu:"Kids Menu",
    HealthMenu:"Health Menu",
    DiabeticMenu:"Diabetic Menu",
    AddressingAllergies:"Addressing Allergies",
    SodexoCouponsAccepted:"Sodexo Coupons Accepted",
    LiveBand:"Live Band",
    Karaoke:"Karaoke",
    Cateringservices:"Catering services",
    WashroomFacility:"Washroom Facility",

    Banquets:"Banquets",
    BanquetsMaxCapacity:"Banquets Max Capacity",
    SeatingCapacity:"Seating Capacity",
    Numberoftables:"Number of tables",
    SubscriptionPlan:"Subscription Plan",
    PackageChosen:"Package Chosen",
    PackagePeriod:"Package Period",
    PaymentDetails:"Payment Details",
    Bar:"Bar",
    BOTRestaurantID:"BOT Restaurant ID",
    SalesPersonName:"Sales Person Name",
    AccountManager:"Account Manager(s)",
    ChainOfRestaurant:"Chain Of Restaurant",
    ShowReservationId:"Show Reservation Id",
    SendWaitlistedURL:"Send Waitlisted URL",
    AuditLogforMaster:"Audit Log for Master",
    AuditLogforTransaction:"Audit Log for Transaction",
    AuditLogforReport:"Audit Log for Report",
    IsOperaInterface:"Is Opera Interface",
    MDMLookUp:"MDM Look Up",
    IsEmailMandatory:"Is Email Mandatory",
    SyncDashboardURL:"Sync Dashboard URL",
    IsDigitalClock:"Is Digital Clock",
    PhotoBorderColor:"Photo Border Color",
    PointsBackgroundColor:"Points Background Color",
    ProfileBandBackgroundColor:"Profile Band Background Color",
    AllergiesOtherAllergies:"Allergies + Other Allergies",
    AccountAboutUs:"Account About Us",
    IsActive:"Is Active",
    RoleID:"Role ID",
    RoleDescription:"Role Description",
    Active:"Active",
    UserID:"User ID",
    UserName:"User Name",
    EmailIDLoginID:"Email ID (Login ID)",
    POSUserId:"POS User Id",
    Password:"Password",
    ConfirmPassword:"Confirm Password",
    Role:"Role",
    Interface:"Interface",
    Restaurant:"Restaurant",
    RetireUser:"Retire User",
    SuperUser:"Super User",
    RoleName: "Role Name",
    RestaurantId:"Restaurant Id",
    RestaurantLogo:"Restaurant Logo",
    RestaurantName:"Restaurant Name",
    EmailofRestaurant:"Email of Restaurant",
    EnableShowLocation:"Enable Show Location",
    OwnSMSAccount:"Own SMS Account",
    OwnEmailAccount:"Own Email Account",
    EnableTicker:"Enable Ticker",
    GroupId:"Group Id",
    ClientId:"Client Id",
    PosCode:"Pos Code",
    InRestoKey:"InResto Key",
    CompulsoryOTPContactTracer:"Compulsory OTP (Contact Tracer)",
    BrandID:"Brand ID",
    GoogleAPIKey:"Google API Key",
    SOLOEscalationNumber:"SOLO! Escalation Number",
    SOLOEscalationEmail:"SOLO! Escalation Email",
    RestaurantShortDescription:"Restaurant Short Description",
    TNCURL:"TNCURL",
    PPURL:"PPURL",
    EnableDelivery:"Enable Delivery",
    EnablePickUP:"Enable PickUP",
    EnableModifyOrderInMerchantApp:"Enable Modify Order In Merchant App",
    CallForServerMessage:"Call For Server Message",
    CallForBillMessage:"Call For Bill Message",
    AllowModifierQuantity:"Allow Modifier Quantity",
    MaxModifierQuantity:"Max Modifier Quantity",
    CurrencySymbol:"Currency Symbol",
    CurrencySymbolText:"Currency Symbol Text",
    EnableTableBooking:"Enable Table Booking",
    ShowInClub:"Show In Club",
    EnableChat:"Enable Chat",
    EnableWallet:"Enable Wallet",
    DishCoMerchant:"DishCo Merchant",
    Facilities:"Facilities",
    RestaurantSettings:"Restaurant Settings",
    Feedback:"Feedback",
    EnableFeedback:"Enable Feedback",
    FeedbackAPIURL:"Feedback API URL",
    FeedbackSubscription:"Feedback Subscription",
    FeedbackForm:"Feedback Form",
    SendFeedbackUrl:"Send Feedback Url",
    IsActiveForFeedback:"IsActiveForFeedback",
    OnlineOrdering:"Online Ordering",
    ThirdPartyChannel:"Third Party Channel",
    ThirdPartyPOS:"Third Party POS",
    ThirdPartyPMS:"Third Party PMS",
    ProfileLookup:"Profile Lookup",
    Analytics:"Analytics",
    EnableAnalytics:"Enable Analytics",
    DashboardAPIURL:"Dashboard API URL",
    IsAllRestaurants:"Is All Restaurants",
    TodaysSalesAPIURL:"Todays Sales API URL",
    OwnersAppClientId:"Owners App Client Id",
    ThirdPartyTransactionSync:"Third Party Transaction Sync",
    TransactionSyncChannel:"Transaction Sync Channel",
    AdvanceOrder:"Advance Order",
    EnableAdvanceOrder:"Enable Advance Order",
    MaxAdvanceOrder:"Max Advance Order",
    AdvanceOrderDefaultTimeSlot:"Advance Order Default Time Slot",
    AboutRestaurant:"About Restaurant",
    EnablePayBill:"Enable Pay Bill",
    RestaurantSafety:"Restaurant Safety",
    CasingForMenuHead:"Casing For Menu Head",
    CasingForMenuItem:"Casing For Menu Item",
    CasingForModifier:"Casing For Modifier",
    CasingForModifierGroup:"Casing For Modifier Group",
    CovidText:"Covid Text",
    // AboutRestaurant:"About Restaurant",
    OwnedBy:"Owned By",

    CopyLocationButton:"Copy Location Button",
    GetDirectionsButton:"Get Directions Button",
    AverageWineCost:"Average Wine Cost",
    AverageBeerCost:"Average Beer Cost",
    OLOWebsiteURL:"OLO Website URL",
    MypospushURL:"Mypospush URL",
    ViewAllOutletsButton:"View All Outlets Button",
    GeoFencingLocationForJustOrder:"GeoFencing Location For Just Order",
    FreeflowTextinSolo:"Freeflow Text in Solo",
    FreeflowModifierForEachMenuItem:"Freeflow Modifier For Each Menu Item",
    UploadBackgroundImage2:"Upload Background Image 2",
    ImageForOrder400x400:"Image For Order(400x400)",
    mageForDineIn400x400:"Image For Dine-In(400x400)",
    ImageForOffer400x400:"Image For Order(400x400)",
    ImageForReserve400x400:"Image For Reserve(400x400)",
    RestaurantTopImage:"Restaurant Top Image",
    OrderTypeSelectionPageBackImage:"Order Type Selection Page Back Image",
    DeliveryChannel:"Delivery Channel",
    SOLOSettings:"SOLO Settings",
    SearchViewType:"Search View Type",
    MenuPageViewType:"Menu Page View Type",
    RestaurantOptionsViewType:"Restaurant Options View Type",
    CityId:"City Id",
    ViewCartStripColor:"View Cart Strip Color",
    ShowAddressAsTable:"Show Address As Table",
    EnableTodaysAdvanceOrder:"Enable Todays Advance Order",
    AskParcelEatHere:"Ask Parcel Eat Here",
    AllowRestaurantSelectionForDelivery:"Allow Restaurant Selection For Delivery",
    // AccountId:"Account Id",
    LocationId:"Location Id",
    SOLOMenuPreferenceSettings:"SOLO Menu Preference Settings",
    AddButtonBackColor:"Add Button Back Color",
    AddButtonForeColor:"Add Button Fore Color",
    MenuQtyBackColor:"Menu Qty Back Color",
    MenuQtyForeColor:"Menu Qty Fore Color",
    MenuHeadForeColor:"Menu Head Fore Color",
    NoofItemsAcrossMobile:"No of Items Across Mobile",
    NoofItemsAcrossWeb:"No of Items Across Web",
    TaxesAndChargesText:"Taxes And Charges Text",
    PackagingChargesLabelText:"Packaging Charges Label Text",
    AdvanceOrderTimeSlotDuration:"Advance Order Time Slot Duration",
    AdvanceOrderJustOrderTimeSlotDuration:"Advance Order Just Order Time Slot Duration",
    ViewAllLocationBackColor:"View All Location Back Color",

    FilterVeganMenuItems:"Filter Vegan Menu Items",
    FilterGlutenFreeMenuItems:"Filter Gluten Free Menu Items",
    FilterSelectSpicyLevel:"Filter Select Spicy Level",
    FilterEggMenuItem:"Filter Egg Menu Item",
    ShowTaxBreakupFlag:"Show Tax Breakup Flag",
    FilterVegMenuItems:"Filter Veg Menu Items",
    FreeDeliveryFlag:"Free Delivery Flag",
    EnableJustOrderAdvanceOrder:"Enable Just Order Advance Order",
    FilterJainMenuItems:"Filter Jain Menu Items",
    AcceptAdvanceOrdersFlag:"Accept Advance Orders Flag",
    FlagRestaurantLogo:"Flag Restaurant Logo",
    DeliveryType:"Delivery Type",
    UploadMenu:"Upload Menu:",
    UploadRestaurantImage:"Upload Restaurant Image:",
    CompanyName:"Company Name",
    CompanyCode:"Company Code",
    Website:"Website",
    TelephoneNo:"Telephone No.",
    AlternateTelephoneNo:"Alternate Telephone No.",
    ContactPerson:"Contact Person",
    AlternateContactPerson:"Alternate Contact Person",    
    Description:"Description",
    OccasionName:"Occasion Name",
    OccasionImage:"Occasion Image",
    Title:"Title",
    GuestImage:"Guest Image",
    FirstName:"First Name",
    LastName:"Last Name",
    MobileNo:"Mobile No.",
    LandLineNo:"LandLine No.",
    Company:"Company",
    OtherContact:"Other Contact",
    OtherEmail:"Other Email",
    Rating:"Rating",
    Designation:"Designation",
    DateOfBirth:"Date Of Birth",
    AnniversaryDate:"Anniversary Date",
    Address:"Address",
    PatronNotes:"Patron Notes",
    Remarks:"Remarks",
    Attachment:"Attachment",
    DefaultValueforPromotionalEmails:"Default Value for Promotional Emails",
    DefaultValueforSharePersonalInfo:"Default Value for Share Personal Info.",
    DefaultValueforPromotionalSMS:"Default Value for Promotional SMS",
    Flag:"Flag",
    FlagImage:"Flag Image",
    FlagMaster:"Flag Master",
    New:"New",
    List:"List",
    Edit:"Edit",
    TableView:"Table View",
    CompanyMaster:"Company Master",
    GuestMaster:"Guest Master",
    OccasionMaster:"Occasion Master",
    GeneralMasters:"General Masters",
    ChannelAccountLinkupMaster:"Channel Account Linkup Master",
    Channel:"Channel",
    DisplayChannelAs:"Display Channel As",
    ImageLogo:"Image Logo",
    CancellationAllowedbefore:"Cancellation Allowed before",
    Editable:"Editable",
    ShareBillDetails:"Share Bill Details",
    // DefaultValueforPromotionalEmails:"Default Value for Promotional Emails",
    FloorMaster:"Floor Master",
    Floor:"Floor",
    FloorImage:"Floor Image",
    RestaurantService:"Restaurant Service",
    Name:"Name",
    Image:"Image",
    TableMaster:"Table Master",
    TableNumber:"Table Number",
    TableDescription:"Table Description",
    Capacity:"Capacity",
    InSmokingArea:"In Smoking Area",
    TableClosed:"Table Closed",
    HideInBlockingSheet:"Hide In Blocking Sheet",
    MealSession:"Meal Session",
    MealStructure:"Meal Structure",
    FromTime:"From Time",
    ToTime:"To Time",
    DefaultMealLength:"Default Meal Length",
    Session:"Session",
    PaxWiseReservationList:"Pax Wise Reservation List",
    ChannelManagementMaster:"Channel Management Master",
    MinAdvanceDays:"Min. Advance Days",
    MaxAdvanceDays:"Max. Advance Days",
    FromDate:"From Date",
    ToDate:"To Date",
    DayOfWeek:"Day Of Week",
    FromSpecialDate:"From Special Date",
    ToSpecialDate:"To Special Date",
    ParameterMaster:"Parameter Master",
    DefaultPax:"Default Pax",
    Weekday:"Weekday",
    AllowBackdatedEntries:"Allow Backdated Entries",
    SMSVendor:"SMS Vendor",
    TriggerforSMS:"Trigger for SMS",
    TriggerforEmail:"Trigger for Email",
    POSInterface:"POS Interface",
    About:"About",
    ContactNumber1:"Contact Number 1",
    ContactNumber2:"Contact Number 2",
    AccountWebsite:"Account Website",
    State:"State",
    NumberofSeats:"Number of Seats",
    Paymodes:"Paymodes",
    BanquetsCapacity:"Banquets Capacity",
    AvgPriceforPintofBeer:"Avg Price for Pint of Beer",
    FineDine:"Fine Dine",
    CoffeeShop:"Coffee Shop",
    Lunch:"Lunch",
    DinnerBuffet:"Dinner Buffet",
    IndoorSeating:"Indoor Seating",
    RooftopSeating:"Rooftop Seating",
    KidsArea:"Kids Area",
    Wheelchairfriendly:"Wheelchair friendly",
    SpecialyabledParking:"Specialy abled Parking",
    VeganMenu:"Vegan Menu",
    JainMenu:"Jain Menu",
    HalalMenu:"Halal Menu",
    KosherMenu:"Kosher Menu",
    BraileMenu:"Braile Menu",
    Livescreening:"Live screening",
    DJ:"DJ",
    GoogleMapURL:"Google Map URL",
    PMSConfig:"PMS Config",
    PMSType:"PMS Type",
    PMSStatus:"PMS Status",
    PMSInterfaceURL:"PMS Interface URL",
    DNSURL:"DNS URL",
    PMSUsername:"PMS Username",
    PMSAPIPassword:"PMS API Password",
    POSConfig:"POS Config",
    POSType:"POS Type",
    POSCode:"POS Code",
    GroupID:"Group ID",
    ClientID:"Client ID",
    POSURL:"POS URL",
    ChannelType:"Channel Type",
    Enable:"Enable",
    OLOforMember:"OLO for Member",
    OLOURL:"OLO URL",
    FreeflowtextinOLO:"Free flow text in OLO",
    DeliveryTime:"Delivery Time",
    OLOMyPOS:"OLO My POS",
    HomeDeliveryArea:"Home Delivery Area",
    MaxDeliveryDistance:"Max Delivery Distance",
    DeliveryAcceptance:"Delivery Acceptance",
    MinimumDeliveryTime:"Minimum Delivery Time",
    MinimumPickupTime:"Minimum Pickup Time",
    MinimumOrderValue:"Minimum Order Value",
    DistanceWiseOrderValue:"Distance Wise Order Value",
    AdvanceOrders:"Advance Orders",
    MaxDaysInAdvance:"Max Days In Advance",
    MyPOSforMember:"MyPOS for Member",
    MyPOSURL:"MyPOS URL",
    FreeflowmodifierforMyPOS:"Free flow modifier for MyPOS",
    GefencingforJustOrder:"Ge-fencing for Just Order",
    Aboutbrand:"About brand",
    Aboutrestaurant:"About restaurant",
    Safetytextfield:"Safety text field",
    ThemeColorForButtons:"Theme Color For Buttons",
    ThemeColorForBanners:"Theme Color For Banners",
    UploadBannerImage:"Upload Banner Image",
    UploadBackgroundImage1:"Upload Background Image 1",
    FromDistance:"From Distance",
    ToDistance:"To Distance",
    EmailTemplateMaster:"Email Template Master",
    TemplateType:"Template Type",
    Subject:"Subject",
    SMSTemplateMaster:"SMS Template Master",
    TemplateName:"Template Name",
    TemplateIdFromPartner:"Template Id From Partner",
    TemplateBody:"Template Body ",
    Curl:"Curl",
    UploadWhatsAppTemplates	:"Upload WhatsApp Templates	",
    VisitStatusCriteriaMaster:"Visit Status Criteria Master",
    V1stVisitDesc:"1st Visit Desc.",
    V1stVisitShortDesc:"1st Visit Short Desc.",
    V2ndVisitDesc:"2nd Visit Desc.",
    V2ndVisitShortDesc:"2nd Visit Short Desc.",
    V2ndVisitCount:"2nd Visit Count",
    V2ndVisitTimeline:"2nd Visit Timeline",
    V3rdVisitDesc:"3rd Visit Desc.",
    V3rdVisitShortDesc:"3rd Visit Short Desc.",
    V3rdVisitCount:"3rd Visit Count",
    V3rdVisitTimeline:"3rd Visit Timeline",
    V4thVisitDesc:"4th Visit Desc.",
    V4thVisitShortDesc:"4th Visit Short Desc.",
    V4thVisitCount:"4th Visit Count",
    PaxWiseReservation:"Pax Wise Reservation",
    PaxFrom:"Pax From",
    PaxTo:"Pax To",
    MealLength:"Meal Length",
    Overwrite:"Overwrite",
    BlockTimeSlots:"Block Time Slots",
    EmailSMSConfig:"Email/SMS Config	",
    EmailPortNo:"Email Port No.",
    EmailFrom:"Email From",
    EmailDisplayName:"Email Display Name",
    SMTPUserName:"SMTP User Name",
    SMTPPassword:"SMTP Password",
    SMTPHost:"SMTP Host",
    EmailBCCAddress:"Email BCC Address",
    SSLEnabled:"SSL Enabled",
    ForSOLO:"For SOLO",
    SMSConfiguration:"SMS Configuration",
    SMSUserName:"SMS User Name",
    SMSPassword:"SMS Password",
    SMSURL:"SMS URL",
    NumberText:"Number Text",
    MessageText:"Message Text",
    ChannelWiseWASMSEmailConfiguration:"Channel Wise WA/SMS/Email Configuration",
    SelectPartner:"Select Partner",
    URLKey:"URL Key",
    AuthenticationCode:"Authentication Code",
    YMFrom:"YM From",
    YMTo:"YM To",
    SenderID:"Sender ID",
    IsActiveNo:"Is Active(No)",
    WhatsAppConfiguration:"WhatsApp Configuration",
    EmailSchedulerMaster:"Email Scheduler Master",
    SchedulerName:"Scheduler Name",
    Time:"Time",
    Days:"Days",
    // To:"To",
    CC:"CC",
    IncludeFeedback:"Include Feedback",
    SeatedReservation:"Seated Reservation",
    CancelledReservation:"Cancelled Reservation",
    RepeatGuest:"Repeat Guest",
    WalkinWithSeatedReservation:"Walkin With Seated Reservation",
    WalkinWithCancelledReservation:"Walkin With Cancelled Reservation",
    GuestListReport:"Guest List Report",
    OrderBy:"Order By",
    Status:"Status",
    Occasion:"Occasion",
    Date:"Date",
    WalkinReport:"WalkIn Report",
    RatingWiseReport:"Rating Wise Report",
    CancellationandNoShowReport	:"Cancellation and No-Show Report	",
    GuestVisitStatus:"Guest Visit Status	",
    FlagWiseGuestListReport	:"Flag Wise Guest List Report	",
    RepeatRegularGuestReport:"Repeat & Regular Guest Report",
    ChannelListReport:"Channel List Report",
    GuestProfileReport:"Guest Profile Report",
    RestaurantFloorPlanMaster	:"Restaurant Floor Plan Master	",
    // RestaurantFloorMapMaster	:"Restaurant Floor Map Master	",
    RestaurantFloorMapMaster	:"Design Your Restaurant Floor",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",
    // :"",

  },
  "fr": {
  },
  "ar": {
  }
}